added a field for the interaction type
pak3nuh/dart_pact_consumer pull request #3
Opened 2021-05-18 13:12 UTC by gtudan

The PactSpec has a field for the interaction type.
https://github.com/pact-foundation/pact-specification/tree/version-4#interactions

The broker accepts PACTs without it, but the JVM-Implementation will fail if the field is missing:
https://github.com/pact-foundation/pact-jvm/blob/d5630e6093abcef20ecec727f6b1c0b79bf5cf2d/core/model/src/main/kotlin/au/com/dius/pact/core/model/V4Pact.kt#L324

2021-05-19 07:34 UTC, pak3nuh requested changes

2021-05-19 07:34 UTC, pak3nuh commented on lib/src/contract_builder_api.dart
> +  ASYNCHRONOUS_MESSAGES,
I think we should keep `SYNCHRONOUS_HTTP` the only option for now.
Other options support different fields and we may start allowing invalid configurations by mistake.

2021-05-19 07:34 UTC, pak3nuh commented on lib/src/contract_builder_api.dart
> +extension InteractionTypeExt on InteractionType {
While I understand the `enum` approach, I think it might not be the best fit.
I'd suggest a class with private constructors and static fields with the options.
```dart
class InteractionType {
  final String value;
  InteractionType._(this.value);

  static InteractionType SYNCHRONOUS_HTTP = InteractionType("Synchronous/HTTP");
}
```
This approach avoids the extension on an enum and a possibly throwing method.

2021-05-19 08:43 UTC, gtudan commented on lib/src/contract_builder_api.dart
> +  ASYNCHRONOUS_MESSAGES,
Good point, I've updated it.

2021-05-19 11:40 UTC, pak3nuh reviewed
LGTM
Can you add an entry in the `validate` method of the `RequestBuilder` class asserting the new field is not null?
Later this is going to be migrated to null safe but for now we have to deal with that :sweat_smile:

2021-05-19 11:50 UTC, gtudan commented
Sure, done!

2021-05-20 07:50 UTC, merged

2021-05-20 07:50 UTC, pak3nuh commented
Merged. Thanks for the effort